#pragma once

#define VIAL_KEYBOARD_UID {0x0C, 0x24, 0x37, 0xD1, 0xF9, 0x8B, 0x9C, 0x31}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 5 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 0 }

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define ENCODER_RESOLUTION 2

#define DYNAMIC_KEYMAP_LAYER_COUNT 7


#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY

#define CHORDAL_HOLD

#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define TAPPING_TERM 200
#define QUICK_TAP_TERM 150
#define COMBO_TERM 40
#define FLOW_TAP_TERM 70

#define COMBO_MUST_TAP_PER_COMBO

//#define MK_COMBINED
//#define MOUSEKEY_DELAY	        150
//#define MOUSEKEY_INTERVAL   	16
//#define MOUSEKEY_FRICTION   	24
//#define MOUSEKEY_MOVE_DELTA	    1
//#define MOUSEKEY_MAX_SPEED  	32
//#define MOUSEKEY_TIME_TO_MAX    32

#define MOUSEKEY_DELAY   	    15
#define MOUSEKEY_INTERVAL	    16
#define MOUSEKEY_MOVE_DELTA 	6
#define MOUSEKEY_MAX_SPEED  	10
#define MOUSEKEY_TIME_TO_MAX	30
